// <auto-generated />
using AnimalShelterApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AnimalShelterApi.Migrations
{
    [DbContext(typeof(AnimalShelterApiContext))]
    [Migration("20231028000942_PaginationModel")]
    partial class PaginationModel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AnimalShelterApi.Models.Cat", b =>
                {
                    b.Property<int>("CatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.HasKey("CatId");

                    b.ToTable("Cats");

                    b.HasData(
                        new
                        {
                            CatId = 1,
                            Age = 7,
                            Name = "Anya",
                            Sex = "Female",
                            Size = "Large"
                        },
                        new
                        {
                            CatId = 2,
                            Age = 10,
                            Name = "Faith",
                            Sex = "Female",
                            Size = "Medium"
                        },
                        new
                        {
                            CatId = 3,
                            Age = 2,
                            Name = "Willow",
                            Sex = "Female",
                            Size = "Medium"
                        },
                        new
                        {
                            CatId = 4,
                            Age = 4,
                            Name = "Spike",
                            Sex = "Male",
                            Size = "Small"
                        },
                        new
                        {
                            CatId = 5,
                            Age = 10,
                            Name = "Giles",
                            Sex = "Male",
                            Size = "Medium"
                        });
                });

            modelBuilder.Entity("AnimalShelterApi.Models.Dog", b =>
                {
                    b.Property<int>("DogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.HasKey("DogId");

                    b.ToTable("Dogs");

                    b.HasData(
                        new
                        {
                            DogId = 1,
                            Age = 5,
                            Name = "Beatrice",
                            Sex = "Female",
                            Size = "Large"
                        },
                        new
                        {
                            DogId = 2,
                            Age = 3,
                            Name = "Winky",
                            Sex = "Male",
                            Size = "Small"
                        },
                        new
                        {
                            DogId = 3,
                            Age = 2,
                            Name = "Hubert",
                            Sex = "Male",
                            Size = "Large"
                        },
                        new
                        {
                            DogId = 4,
                            Age = 4,
                            Name = "Rhapsody",
                            Sex = "Female",
                            Size = "Large"
                        },
                        new
                        {
                            DogId = 5,
                            Age = 7,
                            Name = "Jessica",
                            Sex = "Female",
                            Size = "Medium"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
